server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "http-01-production"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - argocd.samone.store                 # your actual domain
    tls:
      - hosts:
          - argocd.samone.store             # your actual domain
        secretName: argocd-tls

configs:
  cm:
    url: https://argocd.samone.store        # your actual domain
    server.insecure: "false"
  secret:
    argocdServerAdminPassword: Sammy996@    # ArgoCD admin password
